const { skills, projects, dashboards, certificates } = portfolioData;
const icon = `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 3 6.5v5c0 5 3.8 9.5 9 10.5 5.2-1 9-5.5 9-10.5v-5L12 2Zm0 3.2 5.8 2.9-5.8 2.9-5.8-2.9L12 5.2Zm-6 5.5 5 2.5v5.4c-2.9-1.1-5-3.9-5-7.1v-.8Zm7 7.9v-5.4l5-2.5v.8c0 3.2-2.1 6-5 7.1Z"/></svg>`;
const tags = list => list.map(x => `<span class="tag">${x}</span>`).join('');
document.querySelector('#skill-grid').innerHTML = skills.map(s => `<article class="skill-card reveal"><span class="skill-icon">${s.icon}</span><h3>${s.title}</h3><div>${tags(s.items)}</div></article>`).join('');
function artwork(kind) { return `<div class="project-art ${kind}" aria-hidden="true"><div class="art-bar"></div><div class="art-content"><span></span><span></span><span></span><span></span><span></span></div><div class="art-line"></div><small>DATA VIEW</small></div>`; }
function renderProjects(filter = 'All') { const shown = filter === 'All' ? projects : projects.filter(p => p.category.includes(filter)); document.querySelector('#project-grid').innerHTML = shown.map((p, index) => `<article class="project-card reveal"><div class="project-image">${p.screenshots[0] ? `<img src="${p.screenshots[0]}" alt="${p.title} dashboard preview" />` : artwork(p.image)}</div><div class="project-card-content"><div class="project-meta"><span>${p.category[0]}</span><span>Case study ${String(projects.indexOf(p)+1).padStart(2,'0')}</span></div><h3>${p.title}</h3><p>${p.description}</p><div class="tag-list">${tags(p.category)}</div><div class="card-actions">${p.repo ? `<a href="${p.repo}" target="_blank" rel="noreferrer">${icon} GitHub</a>` : '<span class="repo-pending">Repository to be added</span>'}<button data-project="${projects.indexOf(p)}">View project <b>→</b></button></div></div></article>`).join(''); observeReveals(); }
renderProjects();
document.querySelector('#dashboard-grid').innerHTML = dashboards.map(d => `<article class="dashboard-card reveal">${d.image ? `<img src="${d.image}" alt="${d.title} dashboard screenshot" loading="lazy" />` : `<div class="dashboard-placeholder"><span>Dashboard screenshot</span><small>Add image path in data.js</small></div>`}<div><span>${d.tool}</span><h3>${d.title}</h3><p>${d.description}</p></div></article>`).join('');
document.querySelector('#certificate-grid').innerHTML = certificates.map(c => `<article class="certificate-card reveal"><div class="certificate-icon">✓</div><p>Certificate</p><h3>${c.name}</h3><dl><div><dt>Organization</dt><dd>${c.org}</dd></div><div><dt>Date</dt><dd>${c.date}</dd></div></dl>${c.link ? `<a href="${c.link}" target="_blank" rel="noreferrer">View certificate ↗</a>` : '<span class="certificate-pending">Add certificate link</span>'}</article>`).join('');
const dialog = document.querySelector('#project-modal'), modalContent = document.querySelector('#modal-content');
document.querySelector('#project-grid').addEventListener('click', e => { const button = e.target.closest('[data-project]'); if (!button) return; const p = projects[button.dataset.project]; modalContent.innerHTML = `<p class="eyebrow">Project case study</p><h2 id="modal-title">${p.title}</h2><p class="modal-intro">${p.description}</p>${p.screenshots.length ? `<div class="modal-shots">${p.screenshots.map(s=>`<img src="${s}" alt="${p.title} dashboard screenshot" />`).join('')}</div>` : '<div class="modal-image-note">Add project screenshots in <code>data.js</code></div>'}<div class="detail-grid"><section><h3>Business problem</h3><p>${p.problem}</p></section><section><h3>Objective</h3><p>${p.objective}</p></section><section><h3>Dataset</h3><p>${p.dataset}</p></section><section><h3>Data cleaning</h3><p>${p.cleaning}</p></section><section><h3>Transformation</h3><p>${p.transformation}</p></section><section><h3>Analysis</h3><p>${p.analysis}</p></section><section><h3>KPIs & dashboard</h3><p>${p.kpis}</p></section><section><h3>Key insights</h3><p>${p.insights}</p></section><section><h3>Recommendations</h3><p>${p.recommendations}</p></section></div><div class="modal-footer"><div>${tags(p.category)}</div>${p.repo ? `<a class="button primary" href="${p.repo}" target="_blank" rel="noreferrer">Open GitHub repository ↗</a>` : '<span class="repo-pending">Add GitHub URL in data.js</span>'}</div>`; dialog.showModal(); });
document.querySelector('.modal-close').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', e => { if(e.target === dialog) dialog.close(); });
document.querySelectorAll('.project-filters button').forEach(button => button.addEventListener('click', () => { document.querySelector('.project-filters .active').classList.remove('active'); button.classList.add('active'); renderProjects(button.dataset.filter); }));
const nav = document.querySelector('nav'), toggle = document.querySelector('.menu-toggle'); toggle.addEventListener('click', () => { const open = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded', open); toggle.textContent = open ? '×' : '☰'; }); nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰';}));
const theme = document.querySelector('.theme-toggle'); theme.addEventListener('click', () => { const light = document.body.classList.toggle('light'); theme.setAttribute('aria-label', light ? 'Switch to dark mode' : 'Switch to light mode'); localStorage.setItem('portfolio-theme', light ? 'light' : 'dark'); }); if(localStorage.getItem('portfolio-theme') === 'light') theme.click();
function observeReveals(){ document.querySelectorAll('.reveal:not(.visible)').forEach(el => observer.observe(el)); } const observer = new IntersectionObserver(entries => entries.forEach(e => {if(e.isIntersecting){e.target.classList.add('visible'); observer.unobserve(e.target)}}), {threshold:.08}); observeReveals();
