/* Edit this file to add projects, dashboard screenshots, skills, and certificates. */
const portfolioData = {
  skills: [
    { title: 'Programming & analysis', items: ['Python', 'Pandas', 'NumPy', 'Matplotlib'], icon: '⌘' },
    { title: 'Database', items: ['SQL', 'MySQL', 'MySQL Workbench'], icon: '▤' },
    { title: 'Business intelligence', items: ['Power BI', 'DAX', 'Power Query', 'Power BI Service'], icon: '◫' },
    { title: 'Visualization', items: ['Power BI', 'Tableau', 'Advanced Excel'], icon: '◌' },
    { title: 'Data practice', items: ['Data Cleaning', 'Data Modeling', 'EDA', 'KPI Reporting'], icon: '✦' }
  ],
  projects: [
    { title: 'Bank Loan Analytics', category: ['SQL', 'Power BI', 'Excel'], image: 'analytic', repo: 'https://github.com/chinnaobulareddy/Bank_Loan_Analytics', description: 'A lending portfolio analysis structured to surface loan performance, borrower patterns, and decision-ready KPIs.', problem: 'Create a clear view of bank loan data for reviewing lending performance and portfolio patterns.', objective: 'Prepare the dataset and build an analytical dashboard that makes lending measures easy to explore.', dataset: 'Replace with the verified dataset source and field documentation.', cleaning: 'Document missing-value handling, validation rules, and data quality checks used in your analysis.', transformation: 'Document calculated fields, date logic, and any data-model relationships.', analysis: 'Explore loan distribution, status patterns, borrower segments, and time-based performance.', kpis: 'Add verified KPIs such as total applications, funded amounts, repayments, and portfolio status measures.', insights: 'Add only insights supported by your completed analysis and dashboard.', recommendations: 'Add business recommendations grounded in verified project findings.', screenshots: [] },
    { title: 'U.S. Airline Performance Delay Analysis — 2015', category: ['Python', 'SQL', 'Tableau'], image: 'airline', repo: 'https://github.com/chinnaobulareddy/U.S---Airline-Performance-Delay-Analysis-2015', description: 'An investigation into airline delays, performance questions, and operational patterns in 2015 data.', problem: 'Help users examine where and when flight delays occurred within the 2015 airline performance dataset.', objective: 'Use analysis and visualization to answer delay, carrier, airport, and time-period questions.', dataset: 'U.S. airline performance delay data for 2015. Add the final source and data dictionary here.', cleaning: 'Document duplicate checks, date/time preparation, null treatment, and delay-category validation.', transformation: 'Document derived time fields, delay classifications, and aggregations used in the final analysis.', analysis: 'Explore carrier, airport, month, route, and delay-cause patterns.', kpis: 'Add validated measures for flights, delay rate, delay minutes, cancellations, or on-time performance.', insights: 'Add your completed, evidence-based key findings here.', recommendations: 'Add operational recommendations based on your verified findings.', screenshots: [] },
    { title: 'RBI Banking Transactions & Digital Payments Analytics', category: ['Python', 'SQL', 'Power BI'], image: 'banking', repo: '', description: 'Featured workflow mapping banking and digital payment activity from Python preparation through SQL analysis and Power BI reporting.', problem: 'Organize RBI banking and payment datasets into a consistent analytical view across transaction channels.', objective: 'Track monthly banking transaction trends and develop a model that supports clear KPI reporting.', dataset: 'RBI banking/payment datasets covering NEFT, RTGS, internet and mobile banking, ATM, credit/debit cards, and UPI. Period: January–June/July 2026, subject to dataset availability.', cleaning: 'Collect source files, profile quality, standardize bank names, and create a stable bank ID.', transformation: 'Prepare channel-level records, standardize dates, and create analysis-ready tables through Python and SQL.', analysis: 'Analyze monthly trends, channel adoption, bank-level activity, and transaction patterns.', kpis: 'Develop verified transaction volume, value, monthly-change, channel mix, and bank-level measures.', insights: 'Add validated banking transaction insights after the analysis is complete.', recommendations: 'Add recommendations supported by completed monthly and trend analysis.', screenshots: [] },
    { title: 'Sample Superstore Analysis', category: ['Tableau', 'Excel', 'Power BI'], image: 'superstore', repo: '', description: 'A business performance framework for examining sales, profit, customer, product, and regional patterns.', problem: 'Make sales and profitability data easy to review across customers, products, and regions.', objective: 'Build an interactive KPI dashboard that helps identify business patterns and areas for investigation.', dataset: 'Add the source, refresh date, and field documentation for your Superstore dataset.', cleaning: 'Document data validation, category checks, and null-value treatment.', transformation: 'Document calculated metrics, segment logic, and time-period transformations.', analysis: 'Analyze sales, profit, customer behavior, products, and regions.', kpis: 'Add verified sales, profit, margin, customer, product, and regional KPIs.', insights: 'Add only completed dashboard findings here.', recommendations: 'Add decisions or next steps supported by your finished analysis.', screenshots: [] },
    { title: 'Ocean Plastic Dashboard', category: ['Tableau', 'Excel'], image: 'ocean', repo: 'https://github.com/chinnaobulareddy/Data-Analysis-Dashboard', description: 'An interactive Tableau dashboard exploring ocean plastic waste by type, region, depth, and year.', problem: 'Explore the distribution and growth of plastic waste across ocean regions and depths.', objective: 'Present a clear, interactive view of the project dataset to support environmental awareness and exploration.', dataset: 'Ocean plastic pollution data (2015–2025), categorized by plastic type, ocean region, and depth.', cleaning: 'Data cleaning and preprocessing were completed before visualization. Add your exact preparation steps here.', transformation: 'Document the calculated fields and grouping logic used in the Tableau workbook.', analysis: 'Compare waste by type, region, depth, and time to identify notable patterns.', kpis: 'Total waste, waste by type, region, depth, trend, and composition share.', insights: 'The project README describes a rising trend and highlights PE/PVC plus Pacific/Atlantic patterns; verify against your final dashboard before presenting as conclusions.', recommendations: 'Use the dashboard to focus further analysis and interventions on the highest-impact patterns identified in validated data.', screenshots: ['1st project dashboard.png'] }
  ],
  dashboards: [
    { title: 'Ocean Plastic Pollution', tool: 'Tableau', image: '1st project dashboard.png', description: 'Current Tableau dashboard preview. Replace or add exported dashboard images in data.js.' },
    { title: 'Bank Loan Analytics', tool: 'Power BI', image: '', description: 'Screenshot placeholder — add your final Power BI dashboard image path in data.js.' },
    { title: 'RBI Digital Payments', tool: 'Power BI', image: '', description: 'Screenshot placeholder — add your final monthly banking dashboard image path in data.js.' }
  ],
  certificates: [
    { name: 'ExcelR Data Analyst Pro — 6 Months', org: 'ExcelR', date: 'Add issue date', link: '' },
    { name: 'SQL Certification', org: 'Add issuing organization', date: 'Add issue date', link: '' },
    { name: 'Power BI Certification', org: 'Add issuing organization', date: 'Add issue date', link: '' },
    { name: 'Cisco Data Analytics Essentials', org: 'Cisco', date: 'Add issue date', link: '' }
  ]
};
